apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::785271005414:role/eksctl-eksctl-demo-nodegroup-ng-d3-NodeInstanceRole-SRGnsDsM7La9
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::785271005414:role/UdacityFlaskDeployCBKubectlRole
      username: build  
kind: ConfigMap
metadata:
  creationTimestamp: "2023-11-02T21:13:04Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1257"
  uid: 52baf24f-b5af-4d66-882c-d7c654709a92
